# Generated by Django 2.2.8 on 2020-01-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugene', '0004_auto_20200113_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_plural',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rounding',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol_native',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
