# Generated by Django 2.2.8 on 2020-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugene', '0006_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
