# Generated by Django 2.2.8 on 2020-01-13 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+491725784200'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('fax_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+491725784200'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Fax number')),
                ('tax_number', models.CharField(blank=True, max_length=255, verbose_name='Tax number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='Avatar')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+49172578420'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('business_address_street', models.CharField(blank=True, max_length=254, verbose_name='Street')),
                ('business_address_house_number', models.CharField(blank=True, max_length=5, verbose_name='House number')),
                ('business_address_zipecode', models.CharField(blank=True, max_length=5, verbose_name='Zip code')),
                ('business_address_city', models.CharField(blank=True, choices=[('A', 'Aachen'), ('HH', 'Hamburg'), ('H', 'Hannover')], max_length=5, verbose_name='City')),
                ('business_address_country', models.CharField(blank=True, choices=[('DE', 'Germany')], max_length=3, verbose_name='Country')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Position')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Creation Date')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, verbose_name='Invoice Number')),
                ('client_archive_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Archive Name')),
                ('client_archive_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Archive Address')),
                ('client_archive_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Archive Email')),
                ('client_archive_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Archive Phone')),
                ('client_archive_city', models.CharField(blank=True, choices=[('A', 'Aachen'), ('HH', 'Hamburg'), ('H', 'Hannover')], max_length=5, verbose_name='City')),
                ('client_archive_country', models.CharField(blank=True, choices=[('DE', 'Germany')], max_length=3, verbose_name='Country')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Creation date')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Issue Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery date')),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.IntegerField(choices=[(1, 'received'), (2, 'in-progress'), (3, 'delivered'), (4, 'canceled'), (5, 'returned')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Client')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('article_number', models.CharField(blank=True, max_length=255, verbose_name='Article number')),
                ('is_active', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True, max_length=120, verbose_name='Short description')),
                ('description', models.TextField(blank=True, verbose_name='Note')),
                ('availability_start_date', models.DateTimeField(blank=True, null=True, verbose_name='availability Start Date')),
                ('availability_end_date', models.DateTimeField(blank=True, null=True, verbose_name='availability End Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_archive_name', models.TextField(blank=True, null=True, verbose_name='Product Archive Name')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.BigIntegerField(default=1)),
                ('units', models.CharField(blank=True, choices=[('Mass', (('kg', 'Kilogram'), ('g', 'Gram'))), ('Length', (('mm', 'Millimeter'), ('m', 'Meter'))), ('box', 'Box'), ('pallet', 'Pallet'), ('unit', 'Unit'), ('l', 'Litter')], max_length=50, verbose_name='Units')),
                ('tax', models.DecimalField(choices=[(0, '0%'), (7, '7%'), (19, '19%')], decimal_places=2, default=0.0, max_digits=3, verbose_name='Tax')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ecommerce.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_address_street', models.CharField(blank=True, max_length=254, verbose_name='Street')),
                ('business_address_house_number', models.CharField(blank=True, max_length=5, verbose_name='House number')),
                ('business_address_zipecode', models.CharField(blank=True, max_length=5, verbose_name='Zip code')),
                ('business_address_city', models.CharField(blank=True, choices=[('A', 'Aachen'), ('HH', 'Hamburg'), ('H', 'Hannover')], max_length=5, verbose_name='City')),
                ('business_address_country', models.CharField(blank=True, choices=[('DE', 'Germany')], default='DE', max_length=3, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+49172578420'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('type', models.CharField(choices=[('1', 'Invoice & shipping'), ('2', 'Invoice'), ('3', 'Shipping')], default='1', max_length=10, verbose_name='Type')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ecommerce.Client')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
