# Generated by Django 2.2.8 on 2020-01-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200113_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('units', models.CharField(blank=True, choices=[('Mass', (('kg', 'Kilogram'), ('g', 'Gram'))), ('Length', (('mm', 'Millimeter'), ('m', 'Meter'))), ('box', 'Box'), ('pallet', 'Pallet'), ('unit', 'Unit'), ('l', 'Litter')], max_length=50, verbose_name='Units')),
                ('description', models.TextField(blank=True, verbose_name='Note')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Product')),
            ],
        ),
    ]
